export default {
  APP_LOADING: "APP_LOADING",
  POPUP: "POPUP",
  DETAILS: "DETAILS",
  FETCH_CONFIG: "FETCH_CONFIG",
  SAVE_CONFIG: "SAVE_CONFIG",
  TOGGLE_PROGRESS: "TOGGLE_PROGRESS",
  FETCH_BUILDS: "FETCH_BUILDS",
  FETCH_MORE_BUILDS: "FETCH_MORE_BUILDS",
  DETAILS_BUILD: "DETAILS_BUILD",
  LOG_BUILD: "LOG_BUILD",
  NEW_BUILD_ID: "NEW_BUILD_ID",

  INDEX_PAGE_HEADER: "INDEX_PAGE_HEADER",
  BUILD_LOG_PAGE_HEADER: "BUILD_LOG_PAGE_HEADER",
  SETTINGS_PAGE_HEADER: "SETTINGS_PAGE_HEADER",
  BUILD_DETAILS_PAGE_HEADER: "BUILD_DETAILS_PAGE_HEADER",
  GO_TO_SETTINGS: "GO_TO_SETTINGS",
  RUN_BUILD: "RUN_BUILD",
  REBUILD: "REBUILD",

  SITE_NAME: "School CI server",
  SERVER_API: "http://localhost:9999/api",
};
