/**
 * School CI API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export enum BuildStatus {
  Waiting = "Waiting",
  InProgress = "InProgress",
  Success = "Success",
  Fail = "Fail",
  Canceled = "Canceled",
}
// export type BuildStatus =
//   | "Waiting"
//   | "InProgress"
//   | "Success"
//   | "Fail"
//   | "Canceled";

// export const BuildStatus = {
//   Waiting: "Waiting" as BuildStatus,
//   InProgress: "InProgress" as BuildStatus,
//   Success: "Success" as BuildStatus,
//   Fail: "Fail" as BuildStatus,
//   Canceled: "Canceled" as BuildStatus,
// };
