"use strict";
/**
 * School CI API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BuildStatus;
(function (BuildStatus) {
    BuildStatus["Waiting"] = "Waiting";
    BuildStatus["InProgress"] = "InProgress";
    BuildStatus["Success"] = "Success";
    BuildStatus["Fail"] = "Fail";
    BuildStatus["Canceled"] = "Canceled";
})(BuildStatus = exports.BuildStatus || (exports.BuildStatus = {}));
// export type BuildStatus =
//   | "Waiting"
//   | "InProgress"
//   | "Success"
//   | "Fail"
//   | "Canceled";
// export const BuildStatus = {
//   Waiting: "Waiting" as BuildStatus,
//   InProgress: "InProgress" as BuildStatus,
//   Success: "Success" as BuildStatus,
//   Fail: "Fail" as BuildStatus,
//   Canceled: "Canceled" as BuildStatus,
// };
